spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: test
spring.jpa.hibernate.ddl-auto: create-drop
sites:
  - url: http://www.playback.ru
    name: Playback.ru
  - url: https://volochek.life
    name: volochek.life
  - url: http://radiomv.ru
    name: radiomv.ru
  - url: https://ipfran.ru
    name: ipfran.ru
  - url: https://dimonvideo.ru
    name: dimonvideo.ru
  - url: https://nikoartgallery.com
    name: nikoartgallery.com
  - url: https://et-cetera.ru/mobile
    name: et-cetera.ru/mobile
  - url: https://www.lutherancathedral.ru
    name: lutheruncathedral.ru
  - url: https://dombulgakova.ru
    name: dombulgakova.ru
  - url: https://www.svetlovka.ru
    name: svetlovka.ru