spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: src/main/resources/db/migration
    check-location: false
sites:
  - url: http://www.playback.ru
    name: Playback.ru
  - url: https://volochek.life
    name: volochek.life
  - url: http://radiomv.ru
    name: radiomv.ru
  - url: https://ipfran.ru
    name: ipfran.ru
  - url: https://dimonvideo.ru
    name: dimonvideo.ru
  - url: https://nikoartgallery.com
    name: nikoartgallery.com
  - url: https://et-cetera.ru/mobile
    name: et-cetera.ru/mobile
  - url: https://www.lutherancathedral.ru
    name: lutheruncathedral.ru
  - url: https://dombulgakova.ru
    name: dombulgakova.ru
  - url: https://www.svetlovka.ru
    name: svetlovka.ru